### ISSUE TITLE
Исправить сообщения, выводимые программой

### ISSUE THREAD

**Issue by ayemelianov** [selectel/python-selvpcclient#17]
В сообщениях, выводимых программой-клиентом, нужно исправить форму глагола.
Например, Project was deleted  заменяем на Project has been deleted. 
Аналогичные изменения нужны во всех других сообщениях, касающихся удаления объектов.
Соответствующий pull-request уже добавлен (#16).

**Comment by objque** [comment]
Спасибо за работу!
