### ISSUE TITLE
quota optimize возвращает resource not found

### ISSUE THREAD

**Issue by ilya-lesikov** [selectel/python-selvpcclient#18]
При загрузке своих образов на vpc, кроме квоты для `image_gigabytes` есть ещё квота `volume_gigabytes_iso`, которая выставляется автоматически. selvpc client при `quota optimize` пытается изменять и `volume_gigabytes_iso`, на что возвращается `404 Resource not found`.

Техподдержка:
> volume_gigabytes_iso - это не ISO-образы, а жесткие диски с типом ISO. Они создаются только при первичной установке сервера из собственного образа и называются virtual-cd-rom-for-название_сервера. 

Воспроизведение:
1. Создать новый проект
2. Увеличить квоту на образы до 1 ГБ
3. Загрузить в проект образ:
https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
4. Запустить `selvpc quota optimize`

Ожидание:
Возвращает `Nothing to optimize`

Результат:
Возвращает `Resource not found`

**Comment by objque** [comment]
Привет! Спасибо за замечание. В ближайшее время посмотрю.
