### ISSUE TITLE
Возможность получить raw_json от API

### ISSUE THREAD

**Issue by objque** [selectel/python-selvpcclient#2]
На данный момент нельзя получить json от API, без дополнительных преобразований в resource.

Для решения проблемы, предлагаю
1. Добавить во методы **base.Manager** ключ **return_raw** _(по аналогии с post)_
2. Добавить во все остальные менеджеры возможность передать ключ **return_raw** _(по умолчанию return_raw=False)_ и затем пробросить его в httpclient.

**Comment by dstdfx** [comment]
[PR](https://github.com/selectel/python-selvpcclient/pull/3)
