### ISSUE TITLE
Добавить поддержку travis-ci

### ISSUE THREAD

**Issue by objque** [selectel/python-selvpcclient#4]
Необходимо прикрутить поддержку [travis-ci](https://travis-ci.org)
Для начала: проверку pep8 и прогон тестов. (сборку?)
Так же, travis предоставляет классные бейджики с статусами аля **build: pass**
Можно выбрать парочку и добавить в readme

**Comment by dstdfx** [comment]
[PR](https://github.com/selectel/python-selvpcclient/pull/7)
