### ISSUE TITLE
Расхождение add/create в docstring

### ISSUE THREAD

**Issue by objque** [selectel/python-selvpcclient#8]
![image](https://user-images.githubusercontent.com/7000585/27986093-724d6fc2-6402-11e7-98cd-645906a0b038.png)

Ресурсы добавляются (add), проекты, пользователи и роли создаются (create)

**Comment by dstdfx** [comment]
[Fixed commit](https://github.com/selectel/python-selvpcclient/pull/9/commits/45b58a3aa081745efc1cb5d9abd9aa7ee6d1613b)
